[package]
name = "rt-in-one-weekend-rust"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rtow-rust"
path = "src/main.rs"

[dependencies]
rand = "0.9.2"
image = "0.25.6"
rayon = "1.10.0"
clap = { version = "4.5.42", features = ["derive"] }
